/**
 * File generated by Magnet rest2mobile 1.1 - May 22, 2015 10:30:30 PM
 * @see {@link http://developer.magnet.com}
 */

package com.codepath.apps.twitter.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;
import com.magnet.android.mms.controller.RequestSchema.JMeta;
import com.magnet.android.mms.controller.RequestSchema.JParam;

import java.util.Arrays;
import java.util.Collection;

import com.codepath.apps.twitter.model.beans.*;

public class SimpleTwitterApiFactory extends ControllerFactory<SimpleTwitterApi> {
  public SimpleTwitterApiFactory(MagnetMobileClient magnetClient) {
    super(SimpleTwitterApi.class, SimpleTwitterApiSchemaFactory.getInstance().getSchema(), magnetClient);
  }

  // Schema factory for controller SimpleTwitterApi
  public static class SimpleTwitterApiSchemaFactory extends AbstractControllerSchemaFactory {
    private static SimpleTwitterApiSchemaFactory __instance;

    public static synchronized SimpleTwitterApiSchemaFactory getInstance() {
      if(null == __instance) {
        __instance = new SimpleTwitterApiSchemaFactory();
      }

      return __instance;
    }

    private SimpleTwitterApiSchemaFactory() {}

    protected synchronized void initSchemaMaps() {
      if(null != schema) {
        return;
      }

      schema = new RequestSchema();
      schema.setRootPath("");

      //controller schema for controller method favorite
      JMethod method1 = addMethod("favorite",
        "1.1/favorites/create.json",
        "POST",
        FavoriteResult.class,
        null,
        null,
        Arrays.asList("application/json"));
      method1.setBaseUrl("https://api.twitter.com");
      method1.addParam("id",
        "QUERY",
        String.class,
        null,
        "",
        true);
    }

  }

}
