/**
 * File generated by Magnet rest2mobile 1.1 - May 24, 2015 11:23:42 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.apps.twitter.model.beans;


/**
 * Generated from json example
{
  "w" : 340,
  "h" : 226,
  "resize" : "fit"
}

 */

public class Small {

  
  private Integer h;

  
  private String resize;

  
  private Integer w;

  public Integer getH() {
    return h;
  }
  public String getResize() {
    return resize;
  }
  public Integer getW() {
    return w;
  }

  /**
  * Builder for Small
  **/
  public static class SmallBuilder {
    private Small toBuild = new Small();

    public SmallBuilder() {
    }

    public Small build() {
      return toBuild;
    }

    public SmallBuilder h(Integer value) {
      toBuild.h = value;
      return this;
    }
    public SmallBuilder resize(String value) {
      toBuild.resize = value;
      return this;
    }
    public SmallBuilder w(Integer value) {
      toBuild.w = value;
      return this;
    }
  }
}
