/**
 * File generated by Magnet rest2mobile 1.1 - May 22, 2015 10:30:30 PM
 * @see {@link http://developer.magnet.com}
 */

package com.codepath.apps.twitter.model.beans;

import java.util.List;

/**
 * Generated from json example
{
  "urls" : [ {
    "expanded_url" : null,
    "url" : "http://bit.ly/oauth-dancer",
    "indices" : [ 0, 26 ],
    "display_url" : null
  } ]
}

 */

public class EntitiesUrl {

  
  private List<Url> urls;

  public List<Url> getUrls() {
    return urls;
  }

  /**
  * Builder for EntitiesUrl
  **/
  public static class EntitiesUrlBuilder {
    private EntitiesUrl toBuild = new EntitiesUrl();

    public EntitiesUrlBuilder() {
    }

    public EntitiesUrl build() {
      return toBuild;
    }

    public EntitiesUrlBuilder urls(List<Url> value) {
      toBuild.urls = value;
      return this;
    }
  }
}
