/**
 * File generated by Magnet rest2mobile 1.1 - May 22, 2015 10:30:30 PM
 * @see {@link http://developer.magnet.com}
 */

package com.codepath.apps.twitter.model.beans;


/**
 * Generated from json example
{
  "name" : "OAuthDancer",
  "profile_sidebar_fill_color" : "DDEEF6",
  "profile_background_tile" : true,
  "profile_sidebar_border_color" : "C0DEED",
  "profile_image_url" : "http://a0.twimg.com/profile_images/730275945/oauth-dancer_normal.jpg",
  "created_at" : "WedMar0319:37:35+00002010",
  "location" : "SanFrancisco,CA",
  "follow_request_sent" : false,
  "id_str" : "119476949",
  "is_translator" : false,
  "profile_link_color" : "0084B4",
  "entities" : {
    "url" : {
      "urls" : [ {
        "expanded_url" : null,
        "url" : "http://bit.ly/oauth-dancer",
        "indices" : [ 0, 26 ],
        "display_url" : null
      } ]
    ...

 */

public class User {

  
  private Boolean contributors_enabled;

  
  private String created_at;

  
  private Boolean default_profile;

  
  private Boolean default_profile_image;

  
  private String description;

  
  private UserEntities entities;

  
  private Integer favourites_count;

  
  private Boolean follow_request_sent;

  
  private Integer followers_count;

  
  private Boolean following;

  
  private Integer friends_count;

  
  private Boolean geo_enabled;

  
  private Integer id;

  
  private String id_str;

  
  private Boolean is_translator;

  
  private String lang;

  
  private Integer listed_count;

  
  private String location;

  
  private String name;

  
  private Boolean notifications;

  
  private String profile_background_color;

  
  private String profile_background_image_url;

  
  private String profile_background_image_url_https;

  
  private Boolean profile_background_tile;

  
  private String profile_image_url;

  
  private String profile_image_url_https;

  
  private String profile_link_color;

  
  private String profile_sidebar_border_color;

  
  private String profile_sidebar_fill_color;

  
  private String profile_text_color;

  
  private Boolean profile_use_background_image;

  
  private String screen_name;

  
  private Boolean show_all_inline_media;

  
  private Integer statuses_count;

  
@com.google.gson.annotations.SerializedName("protected")
  private Boolean theProtected;

  
  private String time_zone;

  
  private String url;

  
  private Integer utc_offset;

  
  private Boolean verified;

  public Boolean getContributors_enabled() {
    return contributors_enabled;
  }
  public String getCreated_at() {
    return created_at;
  }
  public Boolean getDefault_profile() {
    return default_profile;
  }
  public Boolean getDefault_profile_image() {
    return default_profile_image;
  }
  public String getDescription() {
    return description;
  }
  public UserEntities getEntities() {
    return entities;
  }
  public Integer getFavourites_count() {
    return favourites_count;
  }
  public Boolean getFollow_request_sent() {
    return follow_request_sent;
  }
  public Integer getFollowers_count() {
    return followers_count;
  }
  public Boolean getFollowing() {
    return following;
  }
  public Integer getFriends_count() {
    return friends_count;
  }
  public Boolean getGeo_enabled() {
    return geo_enabled;
  }
  public Integer getId() {
    return id;
  }
  public String getId_str() {
    return id_str;
  }
  public Boolean getIs_translator() {
    return is_translator;
  }
  public String getLang() {
    return lang;
  }
  public Integer getListed_count() {
    return listed_count;
  }
  public String getLocation() {
    return location;
  }
  public String getName() {
    return name;
  }
  public Boolean getNotifications() {
    return notifications;
  }
  public String getProfile_background_color() {
    return profile_background_color;
  }
  public String getProfile_background_image_url() {
    return profile_background_image_url;
  }
  public String getProfile_background_image_url_https() {
    return profile_background_image_url_https;
  }
  public Boolean getProfile_background_tile() {
    return profile_background_tile;
  }
  public String getProfile_image_url() {
    return profile_image_url;
  }
  public String getProfile_image_url_https() {
    return profile_image_url_https;
  }
  public String getProfile_link_color() {
    return profile_link_color;
  }
  public String getProfile_sidebar_border_color() {
    return profile_sidebar_border_color;
  }
  public String getProfile_sidebar_fill_color() {
    return profile_sidebar_fill_color;
  }
  public String getProfile_text_color() {
    return profile_text_color;
  }
  public Boolean getProfile_use_background_image() {
    return profile_use_background_image;
  }
  public String getScreen_name() {
    return screen_name;
  }
  public Boolean getShow_all_inline_media() {
    return show_all_inline_media;
  }
  public Integer getStatuses_count() {
    return statuses_count;
  }
  public Boolean getTheProtected() {
    return theProtected;
  }
  public String getTime_zone() {
    return time_zone;
  }
  public String getUrl() {
    return url;
  }
  public Integer getUtc_offset() {
    return utc_offset;
  }
  public Boolean getVerified() {
    return verified;
  }

  /**
  * Builder for User
  **/
  public static class UserBuilder {
    private User toBuild = new User();

    public UserBuilder() {
    }

    public User build() {
      return toBuild;
    }

    public UserBuilder contributors_enabled(Boolean value) {
      toBuild.contributors_enabled = value;
      return this;
    }
    public UserBuilder created_at(String value) {
      toBuild.created_at = value;
      return this;
    }
    public UserBuilder default_profile(Boolean value) {
      toBuild.default_profile = value;
      return this;
    }
    public UserBuilder default_profile_image(Boolean value) {
      toBuild.default_profile_image = value;
      return this;
    }
    public UserBuilder description(String value) {
      toBuild.description = value;
      return this;
    }
    public UserBuilder entities(UserEntities value) {
      toBuild.entities = value;
      return this;
    }
    public UserBuilder favourites_count(Integer value) {
      toBuild.favourites_count = value;
      return this;
    }
    public UserBuilder follow_request_sent(Boolean value) {
      toBuild.follow_request_sent = value;
      return this;
    }
    public UserBuilder followers_count(Integer value) {
      toBuild.followers_count = value;
      return this;
    }
    public UserBuilder following(Boolean value) {
      toBuild.following = value;
      return this;
    }
    public UserBuilder friends_count(Integer value) {
      toBuild.friends_count = value;
      return this;
    }
    public UserBuilder geo_enabled(Boolean value) {
      toBuild.geo_enabled = value;
      return this;
    }
    public UserBuilder id(Integer value) {
      toBuild.id = value;
      return this;
    }
    public UserBuilder id_str(String value) {
      toBuild.id_str = value;
      return this;
    }
    public UserBuilder is_translator(Boolean value) {
      toBuild.is_translator = value;
      return this;
    }
    public UserBuilder lang(String value) {
      toBuild.lang = value;
      return this;
    }
    public UserBuilder listed_count(Integer value) {
      toBuild.listed_count = value;
      return this;
    }
    public UserBuilder location(String value) {
      toBuild.location = value;
      return this;
    }
    public UserBuilder name(String value) {
      toBuild.name = value;
      return this;
    }
    public UserBuilder notifications(Boolean value) {
      toBuild.notifications = value;
      return this;
    }
    public UserBuilder profile_background_color(String value) {
      toBuild.profile_background_color = value;
      return this;
    }
    public UserBuilder profile_background_image_url(String value) {
      toBuild.profile_background_image_url = value;
      return this;
    }
    public UserBuilder profile_background_image_url_https(String value) {
      toBuild.profile_background_image_url_https = value;
      return this;
    }
    public UserBuilder profile_background_tile(Boolean value) {
      toBuild.profile_background_tile = value;
      return this;
    }
    public UserBuilder profile_image_url(String value) {
      toBuild.profile_image_url = value;
      return this;
    }
    public UserBuilder profile_image_url_https(String value) {
      toBuild.profile_image_url_https = value;
      return this;
    }
    public UserBuilder profile_link_color(String value) {
      toBuild.profile_link_color = value;
      return this;
    }
    public UserBuilder profile_sidebar_border_color(String value) {
      toBuild.profile_sidebar_border_color = value;
      return this;
    }
    public UserBuilder profile_sidebar_fill_color(String value) {
      toBuild.profile_sidebar_fill_color = value;
      return this;
    }
    public UserBuilder profile_text_color(String value) {
      toBuild.profile_text_color = value;
      return this;
    }
    public UserBuilder profile_use_background_image(Boolean value) {
      toBuild.profile_use_background_image = value;
      return this;
    }
    public UserBuilder screen_name(String value) {
      toBuild.screen_name = value;
      return this;
    }
    public UserBuilder show_all_inline_media(Boolean value) {
      toBuild.show_all_inline_media = value;
      return this;
    }
    public UserBuilder statuses_count(Integer value) {
      toBuild.statuses_count = value;
      return this;
    }
    public UserBuilder theProtected(Boolean value) {
      toBuild.theProtected = value;
      return this;
    }
    public UserBuilder time_zone(String value) {
      toBuild.time_zone = value;
      return this;
    }
    public UserBuilder url(String value) {
      toBuild.url = value;
      return this;
    }
    public UserBuilder utc_offset(Integer value) {
      toBuild.utc_offset = value;
      return this;
    }
    public UserBuilder verified(Boolean value) {
      toBuild.verified = value;
      return this;
    }
  }
}
