/**
 * File generated by Magnet rest2mobile 1.1 - May 24, 2015 11:23:42 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.apps.twitter.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import com.jim.apps.twitter.model.beans.*;
import java.util.List;

public interface TwitterClient2 {

  /**
   * Generated from URL GET http://twitter.com/api/1.1
   * GET api/1.1
   * @param listener
   * @return List<MediaResult>
   */
  Call<List<MediaResult>> getMedia(StateChangedListener listener);
}
