/**
 * File generated by Magnet rest2mobile 1.1 - May 22, 2015 10:30:30 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.apps.twitter.models;

import java.util.List;

/**
 * Generated from json example
{
  "urls" : [ "aaa" ]
}

 */

public class Description {

  
  private List<java.lang.String> urls;

  public List<java.lang.String> getUrls() {
    return urls;
  }

  /**
  * Builder for Description
  **/
  public static class DescriptionBuilder {
    private Description toBuild = new Description();

    public DescriptionBuilder() {
    }

    public Description build() {
      return toBuild;
    }

    public DescriptionBuilder urls(List<java.lang.String> value) {
      toBuild.urls = value;
      return this;
    }
  }
}
