/**
 * File generated by Magnet rest2mobile 1.1 - May 22, 2015 10:30:30 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.apps.twitter.models;

import java.io.Serializable;
import java.util.List;

/**
 * Generated from json example
{
  "urls" : [ ],
  "hashtags" : [ "a" ],
  "user_mentions" : [ ]
}

 */

public class Entities implements Serializable {

  
  //private List<java.lang.String> hashtags;

  
  private List<Url> urls;

  private List<Media> media;

  
  private List<User_mention> user_mentions;

//  public List<java.lang.String> getHashtags() {
//    return hashtags;
//  }

  public List<Media> getMedia() {
    return media;
  }

  public List<Url> getUrls() {
    return urls;
  }
  public List<User_mention> getUser_mentions() {
    return user_mentions;
  }

  /**
  * Builder for Entities
  **/
  public static class EntitiesBuilder {
    private Entities toBuild = new Entities();

    public EntitiesBuilder() {
    }

    public Entities build() {
      return toBuild;
    }

//    public EntitiesBuilder hashtags(List<java.lang.String> value) {
//      toBuild.hashtags = value;
//      return this;
//    }
    public EntitiesBuilder urls(List<Url> value) {
      toBuild.urls = value;
      return this;
    }
    public EntitiesBuilder user_mentions(List<User_mention> value) {
      toBuild.user_mentions = value;
      return this;
    }
  }
}
