/**
 * File generated by Magnet rest2mobile 1.1 - May 22, 2015 10:30:30 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.apps.twitter.models;

import java.io.Serializable;
import java.util.List;

/**
 * Generated from json example
{
  "coordinates" : [ 37.871609, -122.25831 ],
  "type" : "Point"
}

 */

public class Geo implements Serializable {

  
  private List<java.lang.Double> coordinates;

  
  private String type;

  public List<java.lang.Double> getCoordinates() {
    return coordinates;
  }
  public String getType() {
    return type;
  }

  /**
  * Builder for Geo
  **/
  public static class GeoBuilder {
    private Geo toBuild = new Geo();

    public GeoBuilder() {
    }

    public Geo build() {
      return toBuild;
    }

    public GeoBuilder coordinates(List<java.lang.Double> value) {
      toBuild.coordinates = value;
      return this;
    }
    public GeoBuilder type(String value) {
      toBuild.type = value;
      return this;
    }
  }
}
