/**
 * File generated by Magnet rest2mobile 1.1 - May 24, 2015 11:23:42 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.apps.twitter.models;


/**
 * Generated from json example
{
  "w" : 800,
  "h" : 532,
  "resize" : "fit"
}

 */

public class Large {

  
  private Integer h;

  
  private String resize;

  
  private Integer w;

  public Integer getH() {
    return h;
  }
  public String getResize() {
    return resize;
  }
  public Integer getW() {
    return w;
  }

  /**
  * Builder for Large
  **/
  public static class LargeBuilder {
    private Large toBuild = new Large();

    public LargeBuilder() {
    }

    public Large build() {
      return toBuild;
    }

    public LargeBuilder h(Integer value) {
      toBuild.h = value;
      return this;
    }
    public LargeBuilder resize(String value) {
      toBuild.resize = value;
      return this;
    }
    public LargeBuilder w(Integer value) {
      toBuild.w = value;
      return this;
    }
  }
}
