/**
 * File generated by Magnet rest2mobile 1.1 - May 24, 2015 11:23:42 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.apps.twitter.models;


/**
 * Generated from json example
{
  "w" : 600,
  "h" : 399,
  "resize" : "fit"
}

 */

public class Medium {

  
  private Integer h;

  
  private String resize;

  
  private Integer w;

  public Integer getH() {
    return h;
  }
  public String getResize() {
    return resize;
  }
  public Integer getW() {
    return w;
  }

  /**
  * Builder for Medium
  **/
  public static class MediumBuilder {
    private Medium toBuild = new Medium();

    public MediumBuilder() {
    }

    public Medium build() {
      return toBuild;
    }

    public MediumBuilder h(Integer value) {
      toBuild.h = value;
      return this;
    }
    public MediumBuilder resize(String value) {
      toBuild.resize = value;
      return this;
    }
    public MediumBuilder w(Integer value) {
      toBuild.w = value;
      return this;
    }
  }
}
