/**
 * File generated by Magnet rest2mobile 1.1 - May 22, 2015 10:30:30 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.apps.twitter.models;


import java.io.Serializable;

/**
 * Generated from json example
{
  "coordinates" : null,
  "truncated" : false,
  "created_at" : "TueAug2821:16:23+00002012",
  "favorited" : false,
  "id_str" : "240558470661799936",
  "in_reply_to_user_id_str" : "123",
  "entities" : {
    "urls" : [ ],
    "hashtags" : [ "a" ],
    "user_mentions" : [ ]
  },
  "text" : "justanothertest",
  "contributors" : null,
  "id" : 240558470661799936,
  "retweet_count" : 0,
  "in_reply_to_status_id_str" : "123",
  "geo" : null,
  "retweeted" : false,
  "in_reply_to_user_id" : null,
    ...

TODO (generated by Magnet r2m) : Property in_reply_to_status_id is ignored because the value is null in the json example.
TODO (generated by Magnet r2m) : Property in_reply_to_screen_name is ignored because the value is null in the json example.
TODO (generated by Magnet r2m) : Property in_reply_to_user_id is ignored because the value is null in the json example.
TODO (generated by Magnet r2m) : Property contributors is ignored because the value is null in the json example.

 */

public class Tweet implements Serializable {

  
  private Coordinates coordinates;

  
  private String created_at;

  
  private Entities entities;

  
  private Boolean favorited;

  
  private Geo geo;

  
  private Long id;

  
  private String id_str;

  
  private String in_reply_to_status_id_str;

  
  private String in_reply_to_user_id_str;

  
  //private Place place;

  
  private Boolean possibly_sensitive;

  
  private Integer retweet_count;

  private Integer favorite_count;

  
  private Boolean retweeted;

  private Tweet retweeted_status;
  
  private String source;

  
  private String text;

  
  private Boolean truncated;

  
  private User user;

  public Coordinates getCoordinates() {
    return coordinates;
  }
  public String getCreated_at() {
    return created_at;
  }
  public Entities getEntities() {
    return entities;
  }
  public Boolean getFavorited() {
    return favorited;
  }

  public Integer getFavorite_count() {
    return favorite_count;
  }

  public Geo getGeo() {
    return geo;
  }
  public Long getId() {
    return id;
  }
  public String getId_str() {
    return id_str;
  }
  public String getIn_reply_to_status_id_str() {
    return in_reply_to_status_id_str;
  }
  public String getIn_reply_to_user_id_str() {
    return in_reply_to_user_id_str;
  }
//  public Place getPlace() {
//    return place;
//  }
  public Boolean getPossibly_sensitive() {
    return possibly_sensitive;
  }
  public Integer getRetweet_count() {
    return retweet_count;
  }
  public Boolean getRetweeted() {
    return retweeted;
  }
  public String getSource() {
    return source;
  }
  public String getText() {
    return text;
  }
  public Boolean getTruncated() {
    return truncated;
  }
  public User getUser() {
    return user;
  }

  public String getFirstPhotoMediaUrl() {
    String mediaUrl = null;
    if(null != getEntities() && null != getEntities().getMedia() && getEntities().getMedia().size() > 0) {
      Media media = getEntities().getMedia().get(0);
      mediaUrl = media.getMedia_url();
    }

    return mediaUrl;
  }

  @Override
  public boolean equals(Object o) {
    if(null == o) {
      return false;
    }

    Tweet theOther = (Tweet) o;
    return theOther.getId().equals(id);
  }

  public void copyFrom(Tweet tweet) {
    this.favorite_count = tweet.getFavorite_count();
    this.favorited = tweet.getFavorited();
    this.retweet_count = tweet.getRetweet_count();
    this.retweeted = tweet.getRetweeted();
  }

  public Tweet getRetweeted_status() {
    return retweeted_status;
  }

  public void setRetweeted_status(Tweet retweeted_status) {
    this.retweeted_status = retweeted_status;
  }

  public void setRetweet_count(Integer retweet_count) {
    this.retweet_count = retweet_count;
  }

  public void setFavorite_count(Integer favorite_count) {
    this.favorite_count = favorite_count;
  }

  public void setRetweeted(Boolean retweeted) {
    this.retweeted = retweeted;
  }

  public void setFavorited(Boolean favorited) {
    this.favorited = favorited;
  }
}
