/**
 * File generated by Magnet rest2mobile 1.1 - May 22, 2015 10:30:30 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.apps.twitter.models;

import java.util.List;

/**
 * Generated from json example
{
  "expanded_url" : null,
  "url" : "http://bit.ly/oauth-dancer",
  "indices" : [ 0, 26 ],
  "display_url" : null
}

 */

public class Url {

  
  private String display_url;

  
  private String expanded_url;

  
  private List<java.lang.Integer> indices;

  
  private String url;

  public String getDisplay_url() {
    return display_url;
  }
  public String getExpanded_url() {
    return expanded_url;
  }
  public List<java.lang.Integer> getIndices() {
    return indices;
  }
  public String getUrl() {
    return url;
  }

  /**
  * Builder for Url
  **/
  public static class UrlBuilder {
    private Url toBuild = new Url();

    public UrlBuilder() {
    }

    public Url build() {
      return toBuild;
    }

    public UrlBuilder display_url(String value) {
      toBuild.display_url = value;
      return this;
    }
    public UrlBuilder expanded_url(String value) {
      toBuild.expanded_url = value;
      return this;
    }
    public UrlBuilder indices(List<java.lang.Integer> value) {
      toBuild.indices = value;
      return this;
    }
    public UrlBuilder url(String value) {
      toBuild.url = value;
      return this;
    }
  }
}
