/**
 * File generated by Magnet rest2mobile 1.1 - May 22, 2015 10:30:30 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.apps.twitter.models;

import java.util.List;

/**
 * Generated from json example
{
  "name" : "Cal",
  "id_str" : "17445752",
  "id" : 17445752,
  "indices" : [ 60, 64 ],
  "screen_name" : "Cal"
}

 */

public class User_mention {

  
  private Integer id;

  
  private String id_str;

  
  private List<java.lang.Integer> indices;

  
  private String name;

  
  private String screen_name;

  public Integer getId() {
    return id;
  }
  public String getId_str() {
    return id_str;
  }
  public List<java.lang.Integer> getIndices() {
    return indices;
  }
  public String getName() {
    return name;
  }
  public String getScreen_name() {
    return screen_name;
  }

  /**
  * Builder for User_mention
  **/
  public static class User_mentionBuilder {
    private User_mention toBuild = new User_mention();

    public User_mentionBuilder() {
    }

    public User_mention build() {
      return toBuild;
    }

    public User_mentionBuilder id(Integer value) {
      toBuild.id = value;
      return this;
    }
    public User_mentionBuilder id_str(String value) {
      toBuild.id_str = value;
      return this;
    }
    public User_mentionBuilder indices(List<java.lang.Integer> value) {
      toBuild.indices = value;
      return this;
    }
    public User_mentionBuilder name(String value) {
      toBuild.name = value;
      return this;
    }
    public User_mentionBuilder screen_name(String value) {
      toBuild.screen_name = value;
      return this;
    }
  }
}
