/**
 * File generated by Magnet rest2mobile 1.1 - May 22, 2015 10:30:30 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.apps.twitter.models;


/**
 * Generated from json example
{
  "url" : {
    "urls" : [ {
      "expanded_url" : null,
      "url" : "http://bit.ly/oauth-dancer",
      "indices" : [ 0, 26 ],
      "display_url" : null
    } ]
  },
  "description" : null
}

 */

public class UserEntities {

  
  private Description description;

  
  private EntitiesUrl url;

  public Description getDescription() {
    return description;
  }
  public EntitiesUrl getUrl() {
    return url;
  }

  /**
  * Builder for UserEntities
  **/
  public static class UserEntitiesBuilder {
    private UserEntities toBuild = new UserEntities();

    public UserEntitiesBuilder() {
    }

    public UserEntities build() {
      return toBuild;
    }

    public UserEntitiesBuilder description(Description value) {
      toBuild.description = value;
      return this;
    }
    public UserEntitiesBuilder url(EntitiesUrl value) {
      toBuild.url = value;
      return this;
    }
  }
}
